Kanto, Johto, Hoenn = input().split()
Kanto = int(Kanto)
Johto = int(Johto)
Hoenn = int(Hoenn)
maisK, maisJ, maisH = input().split()
maisK = int(maisK)
maisJ = int(maisJ)
maisH = int(maisH)
print(Kanto + maisK, Johto + maisJ, Hoenn + maisH)
